version: '3'
services:
  datastore:
    image: singularities/datastore-emulator
    environment:
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
      DATASTORE_PROJECT_ID: my-project-id
    expose:
      - "8081"
  datastore-entity-save:
    build: services/datastore-entity-save
    environment:
      DATASTORE_EMULATOR_HOST: datastore:8081
      DATASTORE_PROJECT_ID: my-project-id
    volumes:
      - ./services/datastore-entity-save/index.js:/index.js
      - ./services/datastore-entity-save/entities.json:/entities.json
    depends_on:
      - datastore